module.exports = {
  guns: [
    {
      id: "1",
      gun_type: "Pistol",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/3/35/Wingman_Icon.png/revision/latest/scale-to-width-down/271?cb=20190906030408",
    },
    {
      id: "2",
      gun_type: "Shotgun",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/9/9d/Mastiff_Icon.png/revision/latest/scale-to-width-down/616?cb=20190906030212",
    },
    {
      id: "3",
      gun_type: "Sub machine gun",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/1/1b/R-99_Icon.png/revision/latest/scale-to-width-down/429?cb=20190906030316",
    },
    {
      id: "4",
      gun_type: "Light machine gun",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/f/f9/Spitfire_Icon.png/revision/latest/scale-to-width-down/524?cb=20190906030341",
    },
    {
      id: "5",
      gun_type: "Assault rifle",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/1/1b/R-301_Icon.png/revision/latest/scale-to-width-down/456?cb=20190906030325",
    },
    {
      id: "6",
      gun_type: "Sniper rifle",
      guns_image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/e/e9/Charge_Rifle_Icon.png/revision/latest/scale-to-width-down/460?cb=20190906025957",
    },
  ],
  ammo_types: [
    { id: "1", ammo_type_name: "Light Rounds" },
    { id: "2", ammo_type_name: "Heavy Rounds" },
    { id: "3", ammo_type_name: "Shotgun Shells" },
    { id: "4", ammo_type_name: "Energy Ammo" },
    { id: "5", ammo_type_name: "Sniper Ammo" },
  ],
  fire_modes: [
    { id: "1", fire_mode_name: "Single" },
    { id: "2", fire_mode_name: "Auto" },
    { id: "3", fire_mode_name: "Burst" },
  ],
  weapons: [
    {
      id: "1",
      gun_id: "1",
      weapon_name: "RE-45 Auto",
      description: "Full-auto pistol",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/3/31/RE-45_Pistol.png/revision/latest/scale-to-width-down/314?cb=20190304181228",
      fire_mode_id: "2",
      ammo_type_id: "1",
      rate_of_fire: 750,
      head_damage: 18,
      body_damage: 12,
      legs_arms_damage: 11,
      base_mag_size: 16,
      with_hop_up: true,
      is_supply_drop_weapon: false,
    },
    {
      id: "2",
      gun_id: "1",
      weapon_name: "P2020",
      description: "Semi-auto pistol",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/d/d3/P2020_Pistol.png/revision/latest/scale-to-width-down/314?cb=20190304181204",
      fire_mode_id: "1",
      ammo_type_id: "1",
      rate_of_fire: 750,
      head_damage: 20,
      body_damage: 15,
      legs_arms_damage: 12,
      base_mag_size: 12,
      with_hop_up: true,
      is_supply_drop_weapon: false,
    },
    {
      id: "3",
      gun_id: "2",
      weapon_name: "EVA-8 Auto",
      description: "Full-auto shotgun",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/7/74/EVA-8_Auto_SG.png/revision/latest/scale-to-width-down/314?cb=20190304180547",
      fire_mode_id: "2",
      ammo_type_id: "3",
      rate_of_fire: 126,
      head_damage: 99,
      body_damage: 63,
      legs_arms_damage: 54,
      base_mag_size: 8,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
    {
      id: "4",
      gun_id: "2",
      weapon_name: "Mastiff Shotgun",
      description: "Powerful semi-auto shotgun",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/7/7b/Mastiff_SG.png/revision/latest/scale-to-width-down/314?cb=20190304180854",
      fire_mode_id: "1",
      ammo_type_id: "3",
      rate_of_fire: 66,
      head_damage: 112,
      body_damage: 88,
      legs_arms_damage: 88,
      base_mag_size: 6,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
    {
      id: "5",
      gun_id: "3",
      weapon_name: "Prowler Burst PDW",
      description: "5-round burst SMG",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/f/f1/Prowler_Burst_SMG.png/revision/latest/scale-to-width-down/314?cb=20190304180338",
      fire_mode_id: "3",
      ammo_type_id: "2",
      rate_of_fire: 795,
      head_damage: 23,
      body_damage: 14,
      legs_arms_damage: 12,
      base_mag_size: 35,
      with_hop_up: true,
      is_supply_drop_weapon: true,
    },
    {
      id: "6",
      gun_id: "3",
      weapon_name: "Volt SMG",
      description: "Energy actuated SMG",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/f/f5/Volt.png/revision/latest/scale-to-width-down/314?cb=20200806211909",
      fire_mode_id: "2",
      ammo_type_id: "4",
      rate_of_fire: 66,
      head_damage: 23,
      body_damage: 15,
      legs_arms_damage: 12,
      base_mag_size: 19,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
    {
      id: "7",
      gun_id: "4",
      weapon_name: "M600 Spitfire",
      description: "Full-auto LMG",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/d/d6/M600_Spitfire_LMG.png/revision/latest/scale-to-width-down/314?cb=20190304180514",
      fire_mode_id: "2",
      ammo_type_id: "2",
      rate_of_fire: 540,
      head_damage: 38,
      body_damage: 19,
      legs_arms_damage: 14,
      base_mag_size: 35,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
    {
      id: "8",
      gun_id: "4",
      weapon_name: "Devotion LMG",
      description: "Full-auto energy LMG",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/8/8c/Devotion_LMG.png/revision/latest/scale-to-width-down/314?cb=20190304180450",
      fire_mode_id: "2",
      ammo_type_id: "4",
      rate_of_fire: 900,
      head_damage: 32,
      body_damage: 16,
      legs_arms_damage: 12,
      base_mag_size: 36,
      with_hop_up: true,
      is_supply_drop_weapon: false,
    },
    {
      id: "9",
      gun_id: "5",
      weapon_name: "30-30 Repeater",
      description: "Semi-auto heavy repeater",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/8/86/30-30_Repeater.png/revision/latest/scale-to-width-down/314?cb=20210118183024",
      fire_mode_id: "1",
      ammo_type_id: "2",
      rate_of_fire: 140,
      head_damage: 100,
      body_damage: 57,
      legs_arms_damage: 43,
      base_mag_size: 6,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
    {
      id: "10",
      gun_id: "5",
      weapon_name: "R-301 Carbine",
      description: "Full-auto with high accuracy",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/a/a4/R-301_Carabine_AR.png/revision/latest/scale-to-width-down/314?cb=20190304143302",
      fire_mode_id: "2",
      ammo_type_id: "1",
      rate_of_fire: 816,
      head_damage: 28,
      body_damage: 14,
      legs_arms_damage: 11,
      base_mag_size: 18,
      with_hop_up: true,
      is_supply_drop_weapon: false,
    },
    {
      id: "11",
      gun_id: "6",
      weapon_name: "Kraber .50-Cal Sniper",
      description: "Powerful bolt-action sniper",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/f/fb/Kraber_SR.png/revision/latest/scale-to-width-down/314?cb=20190304181037",
      fire_mode_id: "1",
      ammo_type_id: "5",
      rate_of_fire: 36,
      head_damage: 435,
      body_damage: 145,
      legs_arms_damage: 116,
      base_mag_size: 4,
      with_hop_up: false,
      is_supply_drop_weapon: true,
    },
    {
      id: "12",
      gun_id: "6",
      weapon_name: "Triple Take",
      description: "Triple-barrel sniper",
      image_url:
        "https://static.wikia.nocookie.net/apexlegends_gamepedia_en/images/4/4a/Tripple_Take_SR.png/revision/latest/scale-to-width-down/314?cb=20190304181131",
      fire_mode_id: "1",
      ammo_type_id: "5",
      rate_of_fire: 72,
      head_damage: 138,
      body_damage: 69,
      legs_arms_damage: 63,
      base_mag_size: 6,
      with_hop_up: false,
      is_supply_drop_weapon: false,
    },
  ],
};
